### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by Beniamiiin**

### CODE REVIEW

**Comment by Beniamiiin** [comment]
@jankaltoun can you review this PR, please?

**Comment by jankaltoun** [comment]
Hey @Beniamiiin ! Thank you so much for the PR! I will review it tomorrow.

**Comment by jankaltoun** [comment]
Hi @Beniamiiin ! Sorry, this took a little longer. Meanwhile I released a new version supporting Alamofire 5. Could you please update the PR?

I have a few more notes:
- Instead of `Framework/AlamofireEasyLogger` can we move the sources to a directory named `Source`?
- Can you please remove the `Carthage/Checkouts` files? I'd rather not have the whole Alamofire in my repo 😅.

**Comment by Beniamiiin** [comment]
@jankaltoun hi. I've updated PR, I think now everything is okay.

**Comment by jankaltoun** [comment]
@Beniamiiin amazing work. Thank you! 🙂

**Comment by jankaltoun** [comment]
FYI: I just released a new version with these changes 🙂 .

**Pull request merged**
